In [3]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
df=pd.read_csv("/content/ecommerce_sales_analytics_5000.csv",
               parse_dates=['order_date'])
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [ ]:
df.shape

(5000, 12)

In [ ]:
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [ ]:
df['revenue'].quantile([0.25,0.5,0.75])

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [ ]:
df['revenue'].mean(),df['revenue'].median()

(np.float64(1021.955148), 796.65)

In [ ]:
df['revenue'].skew()

np.float64(1.0017064603000962)

In [ ]:
df.head(1)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.2

In [ ]:
df.groupby("product_category")['revenue'].describe()

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [ ]:
Q1=df['revenue'].quantile(0.25)
Q3=df['revenue'].quantile(0.75)
IQR=Q3-Q1
IQR

np.float64(1161.1625000000001)

In [ ]:
(Q3 > Q1) and (IQR >0)

np.True_

In [ ]:
df=df.set_index('order_date')

In [ ]:
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[ns]', name='order_date', length=5000, freq=None)

In [ ]:
Monthely_Revenue=df['revenue'].resample("ME").sum()



print("="*100)
Monthely_Revenue

====================================================================================================

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [ ]:
Rolling_revenue=df['revenue'].rolling(3).sum()
print("Rolling Revenue")
print("="*100)
Rolling_revenue

Rolling Revenue
====================================================================================================

order_date
2022-01-01        NaN
2022-01-02        NaN
2022-01-03    2831.65
2022-01-04    3518.35
2022-01-05    3682.81
               ...
2035-09-05     776.95
2035-09-06    2107.70
2035-09-07    2147.27
2035-09-08    2041.91
2035-09-09    1683.34
Name: revenue, Length: 5000, dtype: float64

In [ ]:
df['revenue'].pct_change()

order_date
2022-01-01         NaN
2022-01-02   -0.838520
2022-01-03    1.118875
2022-01-04    2.988360
2022-01-05   -0.817674
                ...
2035-09-05    2.976409
2035-09-06    1.631960
2035-09-07   -0.876749
2035-09-08    1.484267
2035-09-09    1.446157
Name: revenue, Length: 5000, dtype: float64

In [ ]:
df['revenue'].diff()

order_date
2022-01-01        NaN
2022-01-02   -1579.10
2022-01-03     340.25
2022-01-04    1925.55
2022-01-05   -2101.34
               ...
2035-09-05     406.25
2035-09-06     885.73
2035-09-07   -1252.41
2035-09-08     261.32
2035-09-09     632.52
Name: revenue, Length: 5000, dtype: float64

In [ ]:
Monthely_Revenue.index.is_monotonic_increasing

True

In [ ]:
Monthely_Revenue.index.is_unique

True

In [ ]:
Monthely_Revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [ ]:
print(Monthely_Revenue.sum(), df['revenue'].sum)
Monthely_Revenue.sum() <= df['revenue'].sum()

5109775.74 <bound method Series.sum of order_date
2022-01-01    1883.20
2022-01-02     304.10
2022-01-03     644.35
2022-01-04    2569.90
2022-01-05     468.56
               ...
2035-09-05     542.74
2035-09-06    1428.47
2035-09-07     176.06
2035-09-08     437.38
2035-09-09    1069.90
Name: revenue, Length: 5000, dtype: float64>

np.True_

In [ ]:
Q1=df['revenue'].quantile(0.25)
Q3=df['revenue'].quantile(0.75)
IQR=Q3 - Q1
print(IQR)

Lower=Q1 - 1.5 * IQR
Upper=Q3 + 1.5 * IQR
print(f" Lower : {Lower}")
print(f" Upper : {Upper}")
outlier_list=df[(df['revenue'] < Lower) | (df['revenue'] > Upper)]
print(outlier_list)

1161.1625000000001
 Lower : -1387.2162500000002
 Upper : 3257.43375
            order_id  customer_id product_category region  quantity  \
order_date
2022-02-09     10040         1474             Home  North         7
2022-03-11     10070         1241           Beauty   East         7
2022-04-13     10103         1201         Clothing   West         6
2022-05-07     10127         1379         Clothing  South         7
2022-06-07     10158         1779      Electronics  North         7
...              ...          ...              ...    ...       ...
2034-04-26     14499         1182         Clothing   West         7
2034-05-23     14526         1601         Clothing   West         7
2034-12-12     14729         1086         Clothing   East         7
2035-05-16     14884         1146      Electronics  South         7
2035-08-21     14981         1374             Home  North         7

            unit_price  discount payment_method  delivery_days  \
order_date
2022-02-09      584.36      0.11           Card              6
2022-03-11      567.75      0.16           Card              1
2022-04-13      586.65      0.02            COD              8
2022-05-07      506.18      0.02         Wallet              7
2022-06-07      571.07      0.02            COD             10
...                ...       ...            ...            ...
2034-04-26      553.14      0.05           Card              3
2034-05-23      539.44      0.08         Wallet              9
2034-12-12      514.98      0.01           Card              1
2035-05-16      583.31      0.00           Card              5
2035-08-21      525.18      0.10           Card              8

            customer_rating  revenue
order_date
2022-02-09              1.3  3640.56
2022-03-11              4.5  3338.37
2022-04-13              4.1  3449.50
2022-05-07              2.9  3472.39
2022-06-07              4.5  3917.54
...                     ...      ...
2034-04-26              3.7  3678.38
2034-05-23              4.3  3473.99
2034-12-12              3.8  3568.81
2035-05-16              4.4  4083.17
2035-08-21              3.6  3308.63

[67 rows x 11 columns]

In [ ]:
outlier_list.shape

(67, 11)

In [ ]:
outlier_list[['revenue', 'product_category']].head()

            revenue product_category
order_date
2022-02-09  3640.56             Home
2022-03-11  3338.37           Beauty
2022-04-13  3449.50         Clothing
2022-05-07  3472.39         Clothing
2022-06-07  3917.54      Electronics

In [ ]:
df=df[(df['revenue'] >= Lower) & (df['revenue'] <=Upper)]
df.shape

(4933, 11)

In [ ]:
df=pd.read_csv("/content/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [ ]:
numaric_df=df[['quantity','unit_price','discount','delivery_days','revenue']]

In [ ]:

print("\nCorrelation")
print("=" *100)
numaric_df.corr()

Correlation
====================================================================================================

               quantity  unit_price  discount  delivery_days   revenue
quantity       1.000000    0.001498 -0.004302      -0.008748  0.623564
unit_price     0.001498    1.000000  0.013215       0.015623  0.678032
discount      -0.004302    0.013215  1.000000      -0.000382 -0.139296
delivery_days -0.008748    0.015623 -0.000382       1.000000  0.005444
revenue        0.623564    0.678032 -0.139296       0.005444  1.000000

In [ ]:
print("\nCoverince")
print("=" *100)
numaric_df.cov()

Coverince
====================================================================================================

,quantity,unit_price,discount,delivery_days,revenue
quantity,4.082009,0.512237,-0.000881,-0.055733,1040.110589
unit_price,0.512237,28648.733946,0.226823,8.338403,94746.795528
discount,-0.000881,0.226823,0.010283,-0.000122,-11.661466
delivery_days,-0.055733,8.338403,-0.000122,9.943075,14.172711
revenue,1040.110589,94746.795528,-11.661466,14.172711,681589.302978

In [ ]:
numaric_df.corr().sort_values(by='revenue',ascending=False)

               quantity  unit_price  discount  delivery_days   revenue
revenue        0.623564    0.678032 -0.139296       0.005444  1.000000
unit_price     0.001498    1.000000  0.013215       0.015623  0.678032
quantity       1.000000    0.001498 -0.004302      -0.008748  0.623564
delivery_days -0.008748    0.015623 -0.000382       1.000000  0.005444
discount      -0.004302    0.013215  1.000000      -0.000382 -0.139296

In [ ]:
numaric_df.corr().style.background_gradient(cmap='coolwarm')

In [ ]:
numaric_df.corr().values.min(),numaric_df.corr().values.max()

(np.float64(-0.13929560296730714), np.float64(1.0))

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/exam_scores.csv")

In [ ]:
print("First 10 rows of the datasets")
print("="*100)
df.head(10)

First 10 rows of the datasets
====================================================================================================

,student_id,name,gender,age,math_score,science_score,english_score,study_hours,previous_grade
0,1,Alice Johnson,Female,20,85,88,92,15,A
1,2,Bob Smith,Male,19,78,82,75,12,B
2,3,Carol White,Female,21,92,95,89,18,A
3,4,David Brown,Male,20,65,70,68,8,C
4,5,Emma Davis,Female,19,88,85,90,16,A
5,6,Frank Wilson,Male,22,72,75,70,10,B
6,7,Grace Lee,Female,20,95,98,96,20,A
7,8,Henry Taylor,Male,19,58,62,60,6,C
8,9,Ivy Martinez,Female,21,82,80,85,14,B
9,10,Jack Anderson,Male,20,75,78,72,11,B

In [ ]:
print("Data Information ")
print("="*100)
df.info()

Data Information
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      50 non-null     int64
 1   name            50 non-null     object
 2   gender          50 non-null     object
 3   age             50 non-null     int64
 4   math_score      50 non-null     int64
 5   science_score   50 non-null     int64
 6   english_score   50 non-null     int64
 7   study_hours     50 non-null     int64
 8   previous_grade  50 non-null     object
dtypes: int64(6), object(3)
memory usage: 3.6+ KB

In [ ]:
print("Stastical Summary")
print("=" * 100)
df.describe()

Stastical Summary
====================================================================================================

,student_id,age,math_score,science_score,english_score,study_hours
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,20.120000,77.340000,79.140000,77.460000,12.680000
std,14.57738,1.042759,12.979749,11.885525,13.215961,4.564459
min,1.00000,19.000000,45.000000,50.000000,48.000000,4.000000
25%,13.25000,19.000000,67.250000,70.500000,66.500000,9.000000
50%,25.50000,20.000000,80.000000,80.500000,79.500000,13.000000
75%,37.75000,21.000000,88.750000,89.000000,89.750000,16.750000
max,50.00000,22.000000,95.000000,98.000000,96.000000,20.000000

In [ ]:
print("Math Statistics")
print("="*100)
print(df['math_score'].describe())

print("\nKey Observations")
print("="*100)
print(f"Average value (mean) : {df['math_score'].mean():.2f}")
print(f"Median value : {df['math_score'].median()}")
print(f"Minimum value : {df['math_score'].min()}")
print(f"Maximum value : {df['math_score'].max()}")
print(f"Mode value : {df['math_score'].mode()}")

Math Statistics
====================================================================================================
count    50.000000
mean     77.340000
std      12.979749
min      45.000000
25%      67.250000
50%      80.000000
75%      88.750000
max      95.000000
Name: math_score, dtype: float64

Key Observations
====================================================================================================
Average value (mean) : 77.34
Median value : 80.0
Minimum value : 45
Maximum value : 95
Mode value : 0    88
1    90
Name: math_score, dtype: int64

In [ ]:
from scipy import stats

normal_score=[50,60,70,80,90,88,67]
print("Sceniro 1 :Normal Value")
print(f"Score : {normal_score}")
print(f"Mean : {np.mean(normal_score):.2f}")
print(f"Median : {np.median(normal_score)}")
print(f"Mode : {stats.mode(normal_score)}")

outlier_score=[50,60,70,80,90,88,1000]
print("\nSceniro 2 : Outlier Value")
print(f"Score : {outlier_score}")
print(f"Mean : {np.mean(outlier_score):.2f}")
print(f"Median : {np.median(outlier_score)}")

Sceniro 1 :Normal Value
Score : [50, 60, 70, 80, 90, 88, 67]
Mean : 72.14
Median : 70.0
Mode : ModeResult(mode=np.int64(50), count=np.int64(1))

Sceniro 2 : Outlier Value
Score : [50, 60, 70, 80, 90, 88, 1000]
Mean : 205.43
Median : 80.0

In [ ]:
df.columns

Index(['student_id', 'name', 'gender', 'age', 'math_score', 'science_score',
       'english_score', 'study_hours', 'previous_grade'],
      dtype='object')

In [ ]:
print("Comparing Mean and median dor each subject")
print("="*100)
subject=['math_score','science_score','english_score']
for subjects in subject:
  mean_valu=df[subjects].mean()
  median_value=df[subjects].median()
  differnce=abs(mean_valu-median_value)

  print(f"\n{subjects.replace("_"," ").title()}")
  print(f"Mean Value : {mean_valu:.2f}")
  print(f"Median Value : {median_value:.2f}")
  print(f"Difference : {differnce:.2f}")

Comparing Mean and median dor each subject
====================================================================================================

Math Score
Mean Value : 77.34
Median Value : 80.00
Difference : 2.66

Science Score
Mean Value : 79.14
Median Value : 80.50
Difference : 1.36

English Score
Mean Value : 77.46
Median Value : 79.50
Difference : 2.04

In [ ]:
print("Standard Divation for each subject")
print("="*100)

for subjects in subject:
  std_value=df[subjects].std()
  mean_value=df[subjects].mean()
  print(f"\n{subjects.replace('_',' ').title()}")
  print(f"Mean Value : {mean_value:.2f}")
  print(f"Standard Devation : {std_value:.2f}")
  print(f"Interpration are score with : {mean_value:.2f} +- {std_value:.2f}")
  print(f'{mean_value - std_value:.2f} to {mean_value + std_value:.2f}')

Standard Divation for each subject
====================================================================================================

Math Score
Mean Value : 77.34
Standard Devation : 12.98
Interpration are score with : 77.34 +- 12.98
64.36 to 90.32

Science Score
Mean Value : 79.14
Standard Devation : 11.89
Interpration are score with : 79.14 +- 11.89
67.25 to 91.03

English Score
Mean Value : 77.46
Standard Devation : 13.22
Interpration are score with : 77.46 +- 13.22
64.24 to 90.68

In [8]:
df=pd.read_csv("/content/exam_scores.csv")
print("First !0 rows of the Datesets")
print("="*100)
df.head(10)

First !0 rows of the Datesets
====================================================================================================

,student_id,name,gender,age,math_score,science_score,english_score,study_hours,previous_grade
0,1,Alice Johnson,Female,20,85,88,92,15,A
1,2,Bob Smith,Male,19,78,82,75,12,B
2,3,Carol White,Female,21,92,95,89,18,A
3,4,David Brown,Male,20,65,70,68,8,C
4,5,Emma Davis,Female,19,88,85,90,16,A
5,6,Frank Wilson,Male,22,72,75,70,10,B
6,7,Grace Lee,Female,20,95,98,96,20,A
7,8,Henry Taylor,Male,19,58,62,60,6,C
8,9,Ivy Martinez,Female,21,82,80,85,14,B
9,10,Jack Anderson,Male,20,75,78,72,11,B

In [14]:
print("Statistrical summary for all numarical column")
print("="*100)
df.describe()

print("\nKey sobservation")
print(f"Average MAth score {df['math_score'].mean():.2f} ")
print(f"Middle Math score {df['math_score'].median():.2f}")
print(f"Max score in Math{df['math_score'].max():.2f}")
print(f"Min score in Math{df['math_score'].min()}")

Statistrical summary for all numarical column
====================================================================================================

Key sobservation
Average MAth score 77.34
Middle Math score 80.00
Max score in Math95.00
Min score in Math45

In [16]:
print("Science score ")
print("="*100)
print(f"Average Science score {df['science_score'].mean():.2f} ")
print(f"Middle Science score {df['science_score'].median():.2f}")
print()

Science score
====================================================================================================
Average Science score 79.14
Middle Science score 80.50

In [18]:
Mean_Math=df['math_score'].mean()
print(f"Averga value Math {Mean_Math:.2f}")
Median_Math=df['math_score'].median()
print(f"Middle value of math score {Median_Math:.2f}")
Mode_Math=df['math_score'].mode()
print(f"Mode value of math score {Mode_Math.values[0] if len(Mode_Math) >0 else "Not Mode"}")

Averga value Math 77.34
Middle value of math score 80.00
Mode value of math score 88

In [19]:
df.head()

,student_id,name,gender,age,math_score,science_score,english_score,study_hours,previous_grade
0,1,Alice Johnson,Female,20,85,88,92,15,A
1,2,Bob Smith,Male,19,78,82,75,12,B
2,3,Carol White,Female,21,92,95,89,18,A
3,4,David Brown,Male,20,65,70,68,8,C
4,5,Emma Davis,Female,19,88,85,90,16,A

In [24]:
print("Compare Mean and Median for every subject")
print("=" * 60)

subjects = ['math_score', 'science_score', 'english_score']

for subject in subjects:
    mean_value   = df[subject].mean()
    median_value = df[subject].median()
    difference   = abs(mean_value - median_value)

    print(f"\n{subject.replace('_', ' ').title()}")
    print(f"  Mean      : {mean_value:.2f}")
    print(f"  Median    : {median_value:.2f}")
    print(f"  Difference: {difference:.2f}")

    if difference > 2:
        print("  Status    : Door hain — Outlier possible hai ⚠️")
    else:
        print("  Status    : Close hain — Outlier nahi lagta ✅")

Compare Mean and Median for every subject
============================================================

Math Score
  Mean      : 77.34
  Median    : 80.00
  Difference: 2.66
  Status    : Door hain — Outlier possible hai ⚠️

Science Score
  Mean      : 79.14
  Median    : 80.50
  Difference: 1.36
  Status    : Close hain — Outlier nahi lagta ✅

English Score
  Mean      : 77.46
  Median    : 79.50
  Difference: 2.04
  Status    : Door hain — Outlier possible hai ⚠️