In [28]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [29]:
df_row=pd.read_excel("/content/students_data_raw.xlsx")

In [30]:
print("Print Raw data --spot the problem")
print("=" * 100)
df_row

Print Raw data --spot the problem
====================================================================================================

,student_id,name,age,gender,grade,attendance_percentage,city
0,1,John Doe,22,Male,85,92.5,New York
1,2,jane smith,19,female,78,88.0,los angeles
2,3,ALICE JOHNSON,21,Female,92,95.5,Chicago
3,4,Bob Wilson,200,Male,88,85.0,Houston
4,5,charlie brown,20,M,76,90.0,Phoenix
5,6,Diana Prince,22,Female,95,98.5,Philadelphia
6,7,John Doe,22,Male,85,92.5,New York
7,8,Eve Turner,24,F,82,NaN,San Antonio
8,9,Frank Castle,23,male,79,87.5,San Diego
9,10,NaN,25,Female,88,91.0,Dallas
10,11,Grace Lee,21,Female,94,96.0,San Jose
11,12,Henry Adams,22,Male,Invalid,89.5,Austin
12,13,Ivy Chen,20,female,91,94.0,Jacksonville
13,14,Jack Ryan,-5,M,85,88.0,Columbus
14,15,Kate Bishop,23,Female,89,92.0,Fort Worth
15,16,Leo Martinez,22,MALE,87,90.5,Charlotte
16,17,Mia Anderson,21,F,93,97.0,San Francisco
17,18,Ivy Chen,20,female,91,94.0,Jacksonville
18,19,Oscar Isaac,24,Male,80,86.5,Indianapolis
19,20,Paul Rudd,22,male,84,89.0,Seattle

In [31]:
print("Show Infomartion About Data")
print("="*100)
df_row.info()

Show Infomartion About Data
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   name                   19 non-null     object
 2   age                    20 non-null     int64
 3   gender                 20 non-null     object
 4   grade                  20 non-null     object
 5   attendance_percentage  19 non-null     float64
 6   city                   20 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.2+ KB

In [32]:
df_row.isnull().sum()

student_id               0
name                     1
age                      0
gender                   0
grade                    0
attendance_percentage    1
city                     0
dtype: int64

In [33]:
df=df_row.copy()

In [34]:
len(df)

20

In [35]:
print("Missing Value Per Column")
print("="*100)
missing_value=df.isnull().sum()
print(missing_value)
print(f"Missing value {missing_value.sum()}")

Missing Value Per Column
====================================================================================================
student_id               0
name                     1
age                      0
gender                   0
grade                    0
attendance_percentage    1
city                     0
dtype: int64
Missing value 2

In [36]:
print("Stastical Method")
print("="*100)
df.describe()

Stastical Method
====================================================================================================

       student_id         age  attendance_percentage
count    20.00000   20.000000              19.000000
mean     10.50000   29.400000              91.421053
std       5.91608   40.627188               3.738921
min       1.00000   -5.000000              85.000000
25%       5.75000   20.750000              88.500000
50%      10.50000   22.000000              91.000000
75%      15.25000   23.000000              94.000000
max      20.00000  200.000000              98.500000

In [37]:
a=len(df)
print(a)

b=df.shape
print(b)
df.columns

20
(20, 7)

Index(['student_id', 'name', 'age', 'gender', 'grade', 'attendance_percentage',
       'city'],
      dtype='object')

In [38]:
print("\nNames before Cleaning")
print("="*100)
print(df["name"].head(10).to_list())

df['name']=df['name'].str.strip().str.title()
print("\nNames after Cleaning")
print("="*100)
print(df["name"].head(10).to_list())

Names before Cleaning
====================================================================================================
['John Doe', 'jane smith', 'ALICE JOHNSON', 'Bob Wilson', 'charlie brown', 'Diana Prince', 'John Doe', 'Eve Turner', 'Frank Castle', nan]

Names after Cleaning
====================================================================================================
['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Wilson', 'Charlie Brown', 'Diana Prince', 'John Doe', 'Eve Turner', 'Frank Castle', nan]

In [39]:
duplicated_rows=df.columns.difference(['student_id'])
num_duplicated_rows=df.duplicated(subset=duplicated_rows).sum()

print(f"\nNumber Of Duplicated row {num_duplicated_rows}")

if num_duplicated_rows >0:
  print("\n Duplicated Row")
  print(df[df.duplicated(subset=duplicated_rows,keep=False)])

Number Of Duplicated row 2

 Duplicated Row
    student_id      name  age  gender grade  attendance_percentage  \
0            1  John Doe   22    Male    85                   92.5
6            7  John Doe   22    Male    85                   92.5
12          13  Ivy Chen   20  female    91                   94.0
17          18  Ivy Chen   20  female    91                   94.0

            city
0       New York
6       New York
12  Jacksonville
17  Jacksonville

In [40]:
duplicated_rows=df.columns.difference(['student_id'])
rows_before=len(df)
df.drop_duplicates(subset=duplicated_rows,keep="first",inplace=True)
rows_removed=rows_before - len(df)
print(f"\n{rows_removed} duplicated rows removed")

print(f"\nNumber Of Duplicated row {num_duplicated_rows}")

2 duplicated rows removed

Number Of Duplicated row 2

In [47]:
df

,student_id,name,age,gender,grade,attendance_percentage,city
0,1,John Doe,22,Male,85,92.5,New York
1,2,Jane Smith,19,female,78,88.0,los angeles
2,3,Alice Johnson,21,Female,92,95.5,Chicago
3,4,Bob Wilson,200,Male,88,85.0,Houston
4,5,Charlie Brown,20,M,76,90.0,Phoenix
5,6,Diana Prince,22,Female,95,98.5,Philadelphia
7,8,Eve Turner,24,F,82,attendance_percantage,San Antonio
8,9,Frank Castle,23,male,79,87.5,San Diego
10,11,Grace Lee,21,Female,94,96.0,San Jose
11,12,Henry Adams,22,Male,Invalid,89.5,Austin
12,13,Ivy Chen,20,female,91,94.0,Jacksonville
13,14,Jack Ryan,-5,M,85,88.0,Columbus
14,15,Kate Bishop,23,Female,89,92.0,Fort Worth
15,16,Leo Martinez,22,MALE,87,90.5,Charlotte
16,17,Mia Anderson,21,F,93,97.0,San Francisco
18,19,Oscar Isaac,24,Male,80,86.5,Indianapolis
19,20,Paul Rudd,22,male,84,89.0,Seattle

In [42]:
df.dropna(subset=['name'],inplace=True)

In [49]:
df['attendance_percentage'] = pd.to_numeric(df['attendance_percentage'], errors='coerce')
attendance_mean = df['attendance_percentage'].mean()
df['attendance_percentage'] = df['attendance_percentage'].fillna(attendance_mean)

In [50]:
df

,student_id,name,age,gender,grade,attendance_percentage,city
0,1,John Doe,22,Male,85,92.50000,New York
1,2,Jane Smith,19,female,78,88.00000,los angeles
2,3,Alice Johnson,21,Female,92,95.50000,Chicago
3,4,Bob Wilson,200,Male,88,85.00000,Houston
4,5,Charlie Brown,20,M,76,90.00000,Phoenix
5,6,Diana Prince,22,Female,95,98.50000,Philadelphia
7,8,Eve Turner,24,F,82,91.21875,San Antonio
8,9,Frank Castle,23,male,79,87.50000,San Diego
10,11,Grace Lee,21,Female,94,96.00000,San Jose
11,12,Henry Adams,22,Male,Invalid,89.50000,Austin
12,13,Ivy Chen,20,female,91,94.00000,Jacksonville
13,14,Jack Ryan,-5,M,85,88.00000,Columbus
14,15,Kate Bishop,23,Female,89,92.00000,Fort Worth
15,16,Leo Martinez,22,MALE,87,90.50000,Charlotte
16,17,Mia Anderson,21,F,93,97.00000,San Francisco
18,19,Oscar Isaac,24,Male,80,86.50000,Indianapolis
19,20,Paul Rudd,22,male,84,89.00000,Seattle

In [51]:
print("\nMissing value after Cleaning")
print("="*100)
missing_value=df.isnull().sum()
print(missing_value)
print(f"Missing value {missing_value.sum()}")

Missing value after Cleaning
====================================================================================================
student_id               0
name                     0
age                      0
gender                   0
grade                    0
attendance_percentage    0
city                     0
dtype: int64
Missing value 0

In [54]:
print("Before Fixing Grade Cloumn")
print(df[['name','grade']].head(15))

df['grade']=pd.to_numeric(df['grade'],errors='coerce')
grade_median=df['grade'].median()
df['grade']=df['grade'].fillna(grade_median)

print("After Fixing Grade Cloumn")
print(df[['name','grade']].head())

Before Fixing Grade Cloumn
             name    grade
0        John Doe       85
1      Jane Smith       78
2   Alice Johnson       92
3      Bob Wilson       88
4   Charlie Brown       76
5    Diana Prince       95
7      Eve Turner       82
8    Frank Castle       79
10      Grace Lee       94
11    Henry Adams  Invalid
12       Ivy Chen       91
13      Jack Ryan       85
14    Kate Bishop       89
15   Leo Martinez       87
16   Mia Anderson       93
After Fixing Grade Cloumn
            name  grade
0       John Doe   85.0
1     Jane Smith   78.0
2  Alice Johnson   92.0
3     Bob Wilson   88.0
4  Charlie Brown   76.0

In [61]:
print("Students with impossible ages")
print("="*100)

# Step 1: Find impossible ages
impossible_ages = df[(df['age'] < 0) | (df['age'] > 100)]
print(f"Impossible Ages Count: {len(impossible_ages)}")

# Step 2: Get valid ages (18 to 100)
valid_ages = df[(df['age'] >= 18) & (df['age'] <= 100)]['age']

# Step 3: Median calculate
median_age = valid_ages.median()

# Step 4: Replace invalid ages with median
df.loc[(df['age'] < 0) | (df['age'] > 100), 'age'] = median_age

print("\nAfter Fixing Age Column")
print(df[['name', 'age']].head())

Students with impossible ages
====================================================================================================
Impossible Ages Count: 2

After Fixing Age Column
            name  age
0       John Doe   22
1     Jane Smith   19
2  Alice Johnson   21
3     Bob Wilson   22
4  Charlie Brown   20

In [63]:
print("Before Cleaning Gender value")
print(df['gender'].unique())

Before Cleaning Gender value
['Male' 'female' 'Female' 'M' 'F' 'male' 'MALE']

In [73]:
#Standradization

df['gender']=df['gender'].str.strip().str.lower()

 # Corrected typo from 'stripe' to 'strip'

gender_maping={
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female",
    "transgender": "Transgender"
}

df['gender']=df['gender'].replace(gender_maping)
print("After Cleaning Gender value")
print()
print(df['gender'].unique())

After Cleaning Gender value

['Male' 'Female']